import html
import os

class HTMLVisualizer:
    """
    Generates a side-by-side HTML diff report for LHDiff V2.
    """
    
    HEAD_TEMPLATE = """
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>LHDiff Execution Report</title>
        <style>
            body { font-family: 'Consolas', 'Monaco', monospace; font-size: 13px; margin: 20px; }
            h2 { font-family: sans-serif; color: #333; }
            table { width: 100%; border-collapse: collapse; border: 1px solid #ccc; table-layout: fixed; }
            th { background-color: #f4f4f4; padding: 10px; border-bottom: 2px solid #ddd; text-align: left; }
            td { padding: 4px; border: 1px solid #ddd; vertical-align: top; word-wrap: break-word; }
            
            /* Status Colors */
            .split { background-color: #fffde7; } /* Yellow for splits */
            .merge { background-color: #e3f2fd; } /* Blue for merges */
            .empty { background-color: #fbe9e7; color: #aaa; font-style: italic; } /* Red tint for unmatched */
            .match { background-color: #fff; }
            
            .line-num { 
                color: #999; 
                width: 40px; 
                text-align: right; 
                padding-right: 10px; 
                user-select: none; 
                border-right: 1px solid #eee;
                background-color: #fafafa;
            }
            .code-content { white-space: pre-wrap; }
        </style>
    </head>
    <body>
        <h2>LHDiff V2: Visual Line Mapping Report</h2>
        <table>
            <col width="5%">
            <col width="45%">
            <col width="50%">
            <tr>
                <th>Line</th>
                <th>Old Version</th>
                <th>New Version (Mapped)</th>
            </tr>
    """

    FOOT_TEMPLATE = """
        </table>
        <p style="color: #666; font-style: italic; margin-top: 20px;">Generated by LHDiff V2 Visualizer</p>
    </body>
    </html>
    """

    def generate(self, nodes_a, nodes_b, mappings, output_path="report.html"):
        """
        Generates the HTML file.

        Args:
            nodes_a: List of LineNode objects from Old File
            nodes_b: List of LineNode objects from New File
            mappings: List of tuples (old_idx, [new_indices]) from engine.run()
            output_path: Where to save the HTML file.
        """
        html_content = [self.HEAD_TEMPLATE]
        
        # Convert mappings to a dictionary for fast lookup
        map_dict = {m[0]: m[1] for m in mappings}
        
        # We also want to see unmapped old lines
        
        for node_a in nodes_a:
            idx_a = node_a.original_line_number
            content_a = html.escape(node_a.content)
            
            # Get corresponding new lines
            mapped_indices = map_dict.get(idx_a, [])
            
            # Determine Row Class (Split/Merge/Normal)
            row_class = "match"
            if len(mapped_indices) > 1: row_class = "split"
            elif not mapped_indices: row_class = "empty"
            
            # Build the cell for Old File
            row_html = f'<tr class="{row_class}">'
            row_html += f'<td class="line-num">{idx_a}</td>'
            row_html += f'<td class="code-content">{content_a}</td>'
            
            # Build the cell for New File
            if not mapped_indices:
                row_html += '<td class="empty">No Match (Deleted or Moved out of scope)</td>'
            else:
                # Combine multiple mapped lines into one cell (for splits)
                new_content_block = []
                for idx_b in mapped_indices:
                    # Find the node with this line number
                    # Inefficient lookup O(N), but fine for reporting scripts
                    node_b = next((n for n in nodes_b if n.original_line_number == idx_b), None)
                    if node_b:
                        content_b = html.escape(node_b.content)
                        new_content_block.append(f"<span style='color:#007acc; font-weight:bold;'>[{idx_b}]</span> {content_b}")
                
                row_html += f'<td class="code-content">{"<br>".join(new_content_block)}</td>'
            
            row_html += "</tr>"
            html_content.append(row_html)

        html_content.append(self.FOOT_TEMPLATE)
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(html_content))
        
        print(f"[Visualizer] Report generated successfully at: {os.path.abspath(output_path)}")

if __name__ == "__main__":
    # Test stub
    print("This module is intended to be imported by main.py, but can be tested independently.")